version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: nexuserp-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Elamadodedios2005"

    ports:
      - "14330:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: